plugins {
    id 'io.micronaut.build.internal.micrometer-registry'
}

dependencies {
    api libs.micrometer.registry.prometheus
    api projects.micronautMicrometerRegistryPrometheus
    implementation libs.prometheus.metrics.exporter.pushgateway
    implementation libs.prometheus.metrics.config
    implementation libs.prometheus.metrics.core
    implementation libs.prometheus.metrics.exposition.formats
    implementation libs.prometheus.metrics.tracer.common
    testImplementation(mnSerde.micronaut.serde.jackson)
}

micronautBuild {
    binaryCompatibility {
        enabledAfter '5.9.0' // adjust as needed
    }
}
