== Metric Concepts

Key `Micrometer.io` http://micrometer.io/docs/concepts[concepts] include
a http://micrometer.io/docs/concepts#_registry[MeterRegistry] to register and use
meters. A http://micrometer.io/docs/concepts#_meters[Meter] is something that produces metrics.

A MeterRegistry can have some customizations automatically applied.

=== Meter Registry Configurer

* Any bean that implements `MeterRegistryConfigurer` gets applied to every _applicable_ MeterRegistry bean on creation
* The implementation of the MeterRegistryConfigurer `supports()` method determines if the configurer is applied to a particular registry
** If you want all registries to get the customization, simply return return `true`
** Otherwise, you can evaluate the registry for its class type, its class hierarchy, or other criteria.
** Remember you only get one shot for autoconfiguration; i.e. when the bean context is started.
** However, in code, you can apply additional customizations to the registry config

.MeterRegistryConfigurer Interface
[source,java]
----
include::{metricscore}/aggregator/MeterRegistryConfigurer.java[]
----

.Example
[source,java]
----
include::{testsmetricscore}/SimpleMeterRegistryConfigurer.java[]
----

=== Meter Filter

* A meter filter can be used to determine if a Meter is to be added to the registry. See http://micrometer.io/docs/concepts#_meter_filters[Meter Filters]
* Any bean that implements MeterFilter will be applied to all registries when the registry is first created

You can create custom filters similar to the following inside your application.  Micrometer's `MeterFilter` class provides several convenience methods to help with the creation of these filters.

.Example
[source,java]
----
include::{testsmetricscore}/MeterFilterFactory.java[]
----

=== Meter Binder

Meter Binders get applied to Meter Registry to _mix in_ metrics producers. Micrometer.io defines several of these for cross-cutting metrics related to JVM metrics, caches, classloaders, etc. These all extend a simple interface MeterBinder, but these are not auto wired as beans and manual wiring is required given how micrometer is currently implemented.

==== Provided Binders

The following metrics currently have binders and are enabled by default.  The settings listed below can disable the specific metric binders if you do not with to collect or report the specific metrics.

===== Jvm Metrics

The JVM metrics bindings will provide several jvm metrics.

*Control Property*: `micronaut.metrics.binders.jvm.enabled`

.Metrics provided
|=======
|*Name*
| jvm.buffer.count
| jvm.buffer.memory.used
| jvm.buffer.total.capacity
| jvm.classes.loaded
| jvm.classes.unloaded
| jvm.gc.live.data.size
| jvm.gc.max.data.size
| jvm.gc.memory.allocated
| jvm.gc.memory.promoted
| jvm.memory.committed
| jvm.memory.max
| jvm.memory.used
| jvm.threads.daemon
| jvm.threads.live
| jvm.threads.peak
|=======

===== Web Metrics

There is a default web filter provided for web metrics.  All routes, status codes, methods and exceptions will be timed and counted.

*Control Property*: `micronaut.metrics.binders.web.enabled`

.Filter Path
If enabled, be default the path `/**` will be intercepted.  If you wish to change which paths are run through the filter for the server set `micronaut.metrics.http.path`. For the client set `micronaut.metrics.http.client.path`.

*Control Property*: `micronaut.metrics.web.enabled`

.Metrics provided
|=======
|*Name*
| http.server.requests
| http.client.requests
|=======

===== System Metrics

There are multiple metrics that can be separately toggled.

====== Uptime Metrics

The uptime metrics bindings will provide system uptime metrics.

*Control Property*: `micronaut.metrics.binders.uptime.enabled`

.Metrics provided
|=======
|*Name*
| process.uptime
| process.start.time
|=======

===== Processor Metrics

The processor metrics bindings will provide system processor metrics.

*Control Property*: `micronaut.metrics.binders.processor.enabled`

.Metrics provided
|=======
|*Name*
| system.load.average.1m
| system.cpu.usage
| system.cpu.count
| process.cpu.usage
|=======

===== File Descriptor Metrics

The file descriptor metrics bindings will provide system file descriptor metrics.

*Control Property*: `micronaut.metrics.binders.files.enabled`

.Metrics provided
|=======
|*Name*
| process.files.open
| process.files.max
|=======

===== Logback Metrics

The logging metrics bindings will provide logging metrics if using Logback.

*Control Property*: `micronaut.metrics.binders.logback.enabled`

.Metrics provided
|=======
|*Name*
| logback.events
|=======

===== Hibernate Metrics

You can enable metrics for Hibernate by setting the `hibernate.generate_statistics` property to `true` in configuration. For example for the default entity manager:

Enabling Hibernate Metrics
[source,yaml]
----
jpa:
    default:
        properties:
            hibernate:
                generate_statistics: true
----

Micrometer will automatically expose Hibernate statistics. See the source code for https://github.com/micrometer-metrics/micrometer/blob/8b5a2cfd0c8fcc121cb936bb40a04f45571ce073/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/HibernateMetrics.java#L79[HibernateMetrics] for the available metrics.

===== DataSource Metrics

The data source metrics bindings will provide data source pool metrics.

*Control Property*: `micronaut.metrics.binders.jdbc.enabled`

NOTE: There is a different set of pool metric names for HikariCP and other pool providers.

If you are using `io.micronaut.configuration:micronaut-jdbc-hikari` you will get additional pool metrics as HikariCP has built in support for meter registries.

.HikariCP Metrics Provided
|=======
|*Name*
| hikaricp.connections.idle
| hikaricp.connections.pending
| hikaricp.connections
| hikaricp.connections.active
| hikaricp.connections.creation
| hikaricp.connections.max
| hikaricp.connections.min
| hikaricp.connections.usage
| hikaricp.connections.timeout
| hikaricp.connections.acquire
|=======

If you are using `io.micronaut.configuration:micronaut-jdbc-tomcat` or `io.micronaut.configuration:micronaut-jdbc-dbcp` you will get the following metrics

.Generic Pool Metrics provided
|=======
|*Name*
| jdbc.connections.usage
| jdbc.connections.active
| jdbc.connections.max
| jdbc.connections.min
|=======

== Adding Custom Metrics

To add metrics to your application you can inject a MeterRegistry bean to your class and use the provided methods to access counters, timers, etc.

See the Micrometer.io docs at https://micrometer.io/docs for more information.

.Custom Metrics Example
[source,java]
----
include::{testsmetricscore}/IndexController.java[]
----

== Custom Exception Metrics

To report on response codes for custom handled exceptions, implement import io.micronaut.http.HttpResponseProvider.
The default value reported for ExceptionHandlers is 500.

See the Micronaut docs at https://docs.micronaut.io/latest/guide/index.html for more information on ExceptionHandlers.

.ExceptionHandler Reporting Example
[source,java]
----
include::{testsmetricscore}/OutOfStockException.java[]
----

