[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply one of `micrometer-atlas`, `micrometer-graphite`, `micrometer-prometheus`, or `micrometer-statsd` features to enable metrics and preconfigure the selected registry in your project:
----
$ mn create-app my-app --features micrometer-atlas
----
====

The metrics endpoint returns information about the "metrics" of the application. To execute the endpoint, send a GET request to `/metrics`. This returns the metric names registered with the `MeterRegistry` bean.

You can get specific metrics by using `/metrics/[name]`, for example `/metrics/jvm.memory.used`. This would return something like:

.Sample Metric Detail Json
```json
{
  "name": "jvm.memory.used",
  "measurements": [
    {
      "statistic": "VALUE",
      "value": 1.45397552E8
    }
  ],
  "availableTags": [
    {
      "tag": "area",
      "values": [
        "heap",
        "nonheap"
      ]
    },
    {
      "tag": "id",
      "values": [
        "Compressed Class Space",
        "PS Survivor Space",
        "PS Old Gen",
        "Metaspace",
        "PS Eden Space",
        "Code Cache"
      ]
    }
  ]
}
```

You can further limit the metric by using a tag like `/metrics/jvm.memory.used?tag=id:PS%20Old%20Gen`.

.Sample Metric Detail Json
```json
{
  "name": "jvm.memory.used",
  "measurements": [
    {
      "statistic": "VALUE",
      "value": 1.1434488E7
    }
  ],
  "availableTags": [
    {
      "tag": "area",
      "values": [
        "heap"
      ]
    }
  ]
}
```

You may even use multiple or nested tags, for example `/metrics/jvm.memory.used?tag=id:PS%20Old%20Gen&tag=area:heap`.

.Sample Metric Detail Json
```json
{
  "name": "jvm.memory.used",
  "measurements": [
    {
      "statistic": "VALUE",
      "value": 1.1434488E7
    }
  ]
}
```

== Configuration

Currently, the metrics endpoint is only enabled if you include the `micrometer-core` (or one of the typed registries such as `micrometer-registry-statsd`, `micrometer-registry-graphite`, etc.) AND the `management` dependencies. You must also enable the global metrics flag (`true` by default).

.Property

[configuration]
----
micronaut:
  metrics:
    enabled: true
----

dependency:micronaut-micrometer-core[groupId="io.micronaut.micrometer"]

`micronaut-micrometer-registry-statsd` (or any other registry) also pulls in `micronaut-micrometer-core`, so the explicit `micronaut-micrometer-core` dependency above is only included to make the example verbose:

dependency:micronaut-micrometer-registry-statsd[groupId="io.micronaut.micrometer"]

The `micronaut-management` dependency is also required to enable the endpoint:

dependency:micronaut-management[groupId="io.micronaut"]

To configure the metrics endpoint, supply configuration through `endpoints.metrics`.

.Metrics Endpoint Configuration Example
[configuration]
----
endpoints:
  metrics:
    enabled: Boolean
    sensitive: Boolean
----
