plugins {
    id 'io.micronaut.build.internal.micrometer-module'
}

dependencies {
    annotationProcessor mn.micronaut.graal

    api projects.micronautMicrometerAnnotation
    implementation libs.managed.micrometer.observation

    implementation mn.reactor
    implementation mn.micronaut.core.reactive
    implementation mn.micronaut.context

    compileOnly(libs.managed.micrometer.tracing)

    testAnnotationProcessor mn.micronaut.inject.java
    testAnnotationProcessor projects.micronautMicrometerAnnotation
    testImplementation mnReactor.micronaut.reactor
    testImplementation mnSerde.micronaut.serde.jackson
    testImplementation(libs.managed.micrometer.observation.test) {
        exclude group: 'org.junit.jupiter', module: 'junit-jupiter'
    }
    testImplementation libs.managed.micrometer.tracing
    testImplementation mnTest.micronaut.test.junit5
    testRuntimeOnly    mnTest.junit.jupiter.engine
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
