plugins {
    id 'io.micronaut.build.internal.micrometer-module'
}

dependencies {
    annotationProcessor mn.micronaut.graal

    api projects.micronautMicrometerObservation
    implementation libs.managed.micrometer.observation
    implementation libs.managed.datasource.micrometer

    testAnnotationProcessor mn.micronaut.inject.java
    testAnnotationProcessor projects.micronautMicrometerAnnotation
    testAnnotationProcessor mnData.micronaut.data.processor
    testImplementation libs.managed.micrometer.observation.test
    testImplementation projects.micronautMicrometerCore
    testImplementation mnData.micronaut.data.jdbc
    testImplementation mnSql.micronaut.jdbc.tomcat
    testImplementation libs.managed.micrometer.tracing
    testImplementation libs.managed.micrometer.observation.test

    testRuntimeOnly mnSql.h2
}

micronautBuild {
    binaryCompatibility {
        enabled.set(false)
    }
}
