plugins {
    id 'io.micronaut.build.internal.micrometer-registry'
}

dependencies {
    api libs.micrometer.registry.prometheus
    testImplementation(mnSerde.micronaut.serde.jackson)

    constraints {
        api libs.managed.prometheus.metrics.config
        api libs.managed.prometheus.metrics.core
        api libs.managed.prometheus.metrics.model
        api libs.managed.prometheus.metrics.tracer.common
        runtimeOnly libs.managed.prometheus.metrics.exposition.formats
    }
}
