You can include the Kairos reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-kairos`

dependency:micronaut-micrometer-registry-kairos[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.kairos`. The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosConfig.java[KairosConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|uri | Kairos server URI. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|descriptions | Whether meter descriptions should be sent to InfluxDB. Disable to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example Kairos Config
[configuration]
----
micronaut:
  metrics:
    enabled: true
    export:
      kairos:
        enabled: true
        uri: http://localhost:8080/api/v1/datapoints
        step: PT1M
----
