You can include the Elastic reporter via `io.micronaut.configuration:micronaut-micrometer-registry-elastic:${micronaut.version}`

dependency:micronaut-micrometer-registry-elastic[groupId="io.micronaut.configuration"]

You can configure this reporter using `micronaut.metrics.export.elastic`.  The most commonly changed configuration properties are listed below, but see
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticConfig.java[ElasticConfig]
for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|descriptions | Boolean if meter descriptions should be sent to InfluxDB. Turn this off to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example Elastic Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      elastic:
        enabled: true
        step: PT1M
----
