You can include the Dynatrace reporter via `io.micronaut.configuration:micronaut-micrometer-registry-dynatrace:${micronaut.version}`

dependency:micronaut-micrometer-registry-dynatrace[groupId="io.micronaut.configuration"]

You can configure this reporter using `micronaut.metrics.export.dynatrace`. The most commonly changed configuration properties are listed below, but see
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceConfig.java[DynatraceConfig]
for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|apiToken | Dynatrace Api Token. Required.
|uri | Dynatrace server URI. Required.
|decideId | Device Id to be reported. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|descriptions | Boolean if meter descriptions should be sent to InfluxDB. Turn this off to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example Dynatrace Config
[source,yml]
----
endpoints:
  prometheus:
    sensitive: false
micronaut:
  metrics:
    enabled: true
    export:
      dynatrace:
        enabled: true
        apiToken: ${DYNATRACE_DEVICE_API_TOKEN}
        uri: ${DYNATRACE_DEVICE_URI}
        deviceId: ${DYNATRACE_DEVICE_ID}
        step: PT1M
----
