You can include the Kairos reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-kairos`

dependency:micronaut-micrometer-registry-kairos[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.kairos`. The most commonly changed configuration properties are listed below, but see
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-kairos/src/main/java/io/micrometer/kairos/KairosConfig.java[KairosConfig]
for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|uri | Kairos server uri. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|descriptions | Boolean if meter descriptions should be sent to InfluxDB. Turn this off to minimize the amount of data sent on each scrape. Default: `true`
|=======


.Example Kairos Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      kairos:
        enabled: true
        uri: http://localhost:8080/api/v1/datapoints
        step: PT1M
----
