You can include the Cloudwatch reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-cloudwatch`

dependency:micronaut-micrometer-registry-cloudwatch[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.cloudwatch`.  The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchConfig.java[CloudWatchConfig] for more options

|=======
|*Name* |*Description*
|enabled | Boolean whether to enable the reporter. Could disable to local dev for example. Default: `true`
|namespace | String Namespace that will show up in cloudwatch for these metrics. Default: `micronaut`.
|batchSize | Number Number of metrics to send in a batch to Cloudwatch. Default: `20` Matches max limit found on https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html[Cloudwatch API Reference].
|=======

.Example Cloudwatch Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: true
        namespace: myAwesomeAppMetrics
        batchSize: 10
----
