You can include the New Relic reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-new-relic`

dependency:micronaut-micrometer-registry-new-relic[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.newrelic`. The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicConfig.java[NewRelicConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|apiKey | New Relic API key. Required.
|accountId | New Relic account ID. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|descriptions | Whether meter descriptions should be sent to InfluxDB. Disable to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example New Relic Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      newrelic:
        enabled: true
        apiKey: ${NEWRELIC_API_KEY}
        accountId: ${NEWRELIC_ACCOUNT_ID}
        step: PT1M
----
