You can include the Influx reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-influx`

dependency:micronaut-micrometer-registry-influx[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.influx`. The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxConfig.java[InfluxConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|descriptions | Whether meter descriptions should be sent to InfluxDB. Disable to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example Influx Config
[configuration]
----
micronaut:
  metrics:
    enabled: true
    export:
      influx:
        enabled: true
        step: PT1M
----
