You can include the Wavefront reporter via `io.micronaut.configuration:micronaut-micrometer-registry-wavefront:${micronaut.version}`

dependency:micronaut-micrometer-registry-wavefront[groupId="io.micronaut.configuration"]

You can configure this reporter using `micronaut.metrics.export.wavefront`. The most commonly changed configuration properties are listed below, but see
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java[WavefrontConfig]
for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|apiToken | Wavefront Api token. Required.
|uri |Wavefront service uri. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|descriptions | Boolean if meter descriptions should be sent to InfluxDB. Turn this off to minimize the amount of data sent on each scrape. Default: `true`
|=======


.Example Wavefront Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      wavefront:
        enabled: true
        apiToken: ${WAVEFRONT_API_TOKEN}
        uri: https://longboard.wavefront.com
        step: PT1M
----
