You can include the StatsD reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-statsd`

dependency:micronaut-micrometer-registry-statsd[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.statsd`. The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdConfig.java[StatsdConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|flavor |The type of metric to use (`datadog`, `etsy` or `telegraf`). Default: `datadog`
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|host |The StatsD server. Default: `localhost`
|port |The StatsD port. Default: `8125`
|=======

.Example Statsd Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      statsd:
        enabled: true
        flavor: datadog
        step: PT1M
        host: localhost
        port: 8125
----
