A New Relic Registry using https://github.com/newrelic/micrometer-registry-newrelic[New Relic's own Micrometer Registry] rather than the New Relic registry provided by the Micrometer project.

You can include the New Relic Telemetry reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-new-relic-telemetry`

dependency:micronaut-micrometer-registry-new-relic-telemetry[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.newrelic`. The most commonly changed configuration properties are listed below, but see https://github.com/newrelic/micrometer-registry-newrelic/blob/main/src/main/java/com/newrelic/telemetry/micrometer/NewRelicRegistryConfig.java[NewRelicRegistryConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|apiKey | New Relic API key. Required.
|serviceName| The service name this registry will report as in New Relic.
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|=======

.Example New Relic Telemetry Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      newrelic:
        enabled: true
        apiKey: ${NEWRELIC_API_KEY}
        serviceName: My Micronaut Service
        step: PT1M
----
