You can include the SignalFx reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-signalfx`

dependency:micronaut-micrometer-registry-signalfx[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.signalfx`. The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-signalfx/src/main/java/io/micrometer/signalfx/SignalFxConfig.java[SignalFxConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|accessToken | SignalFX access token. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|descriptions | Whether meter descriptions should be sent to InfluxDB. Disable to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example SignalFx Config
[configuration]
----
micronaut:
  metrics:
    enabled: true
    export:
      signalfx:
        enabled: true
        accessToken: ${SIGNALFX_API_TOKEN}
        step: PT1M
----
