You can include the Wavefront reporter via `io.micronaut.micrometer:micronaut-micrometer-registry-wavefront`

dependency:micronaut-micrometer-registry-wavefront[groupId="io.micronaut.micrometer"]

You can configure this reporter using `micronaut.metrics.export.wavefront`. The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontConfig.java[WavefrontConfig] for more options.

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter, for example per-environment or for local development. Default: `true`
|apiToken | Wavefront API token. Required.
|uri |Wavefront service URI. Required.
|step |How frequently to report metrics. Default: `PT1M` (1 min). See `java.time.Duration#parse(CharSequence)`
|descriptions | Whether meter descriptions should be sent to InfluxDB. Disable to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example Wavefront Config
[configuration]
----
micronaut:
  metrics:
    enabled: true
    export:
      wavefront:
        enabled: true
        apiToken: ${WAVEFRONT_API_TOKEN}
        uri: https://longboard.wavefront.com
        step: PT1M
----
